### ISSUE TITLE
Update this repo to sync with pypi release

### ISSUE THREAD

**Issue by FantasqueX** [mborgerson/pyxbe#14]
I would like to make a ArchLinux pakage for this repo. It's strange that this repo only tags version 0.0.2 while pypi distributes a version of 0.0.3 and source code is not the same for example `setup.cfg` . What's more, angr/cle pins version of pyxbe to 0.0.2. I hope source code contained in this repo sync with pypi and tags a release of 0.0.3 as well.

**Comment by mborgerson** [comment]
Thanks, I'll set up the automation for pypi

**Comment by mborgerson** [comment]
Done
